from enum import Enum


class Category(Enum):
    """ 愛情 歡樂向 冒险 奇幻 百合 校园 科幻 東方 生活 格鬥 轻小说 耽美
    悬疑 神鬼 职场 其他 萌系 治愈 長條 四格 舰娘 TL 节操 竞技 搞笑 伪娘
    热血 後宮 美食 性转换 励志 侦探 AA 彩色 音乐舞蹈 异世界 战争
     历史 机战 惊悚 都市 C99 恐怖 魔幻 穿越 C97 重生 C96 宅系
     武侠 生存 C98 C95 FATE 转生 無修正 仙侠 LoveLive
    """
    LOVE = "aiqing"
    FUN = "huanlexiang"
    ADVENTURE = "maoxian"
    FANTASY = "qihuan"
    YURI = "baihe"
    SCHOOL = "xiaoyuan"
    SCIENCE = "kehuan"
    TOUHOU = "dongfang"
    LIFE = "shenghuo"
    FIGHT = "gedou"
    LIGHT_NOVEL = "qingxiaoshuo"
    BL = "danmei"
    SUSPENSE = "xuanyi"
    GOD_AND_GHOST = "shengui"
    WORK = "zhichang"
    OTHER = "qita"
    CUTE = "mengxi"
    SOFT = "zhiyu"
    LONG_PICTURE = "changtiao"
    FOUR_GRID = "sige"
    SHIP_GIRL = "jianniang"
    TL = "teenslove"
    JIE_CAO = "jiecao"
    competitive = "jingji"
    FUNNY = "gaoxiao"
    OTOKONOKO = "weiniang"
    HOT_BLOOD = "reexue"
    HAREM = "hougong"
    FOOD = "meishi"
    TS = "xingzhuanhuan"
    ENCOURAGE = "lizhi"
    DETECTIVE = "zhetan"
    AA = "aa"
    COLOR = "COLOR"
    MUSIC_AND_DANCE = "yinyuewudao"
    ISEKAI = "yishijie"
    WAR = "zhanzheng"
    HISTORY = "lishi"
    MACHINE = "jizhan"
    SCARY = "jingsong"
    CITY = "dushi"
    C99 = "comiket99"
    HORRIBLE = "恐怖"
    MYSTERY = "mohuan"
    CROSS = "chuanyue"
    C97 = "comiket97"
    RESPAWN = "chongsheng"
    C96 = "comiket96"
    OTAKU = "zhaixi"
    WU_XIA = "wuxia"
    SURVIVE = "shengcun"
    C98 = "C98"
    C85 = "comiket95"
    FATE = "fate"
    METEMPSYCHOSIS = "zhuansheng"
    UNCENSORED = "Uncensored"
    XIAN_XIA = "xianxia"
    LOVE_LIVE = "lovelive"



